version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartmenubot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./audio:/app/audio
      - ./videos:/app/videos
    command: python -m app.bot
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
