# fly.toml app configuration file generated for fly-log-shipper-delicate-glitter-2879 on 2025-06-01T23:17:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-log-shipper-delicate-glitter-2879"
primary_region = "otp"

[build]
  image = "flyio/log-shipper:latest"

[[services]]
  internal_port = 8686
  http_checks = []
