# fly.toml app configuration file generated for fly-log-shipper-twilight-surf-5889 on 2025-06-01T21:11:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-log-shipper-twilight-surf-5889"
primary_region = "cdg"

[build]
  image = "flyio/log-shipper:latest"

[[services]]
  http_checks = []
  internal_port = 8686
