name: Deploy to Hetzner on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 91.99.6.156 >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh root@91.99.6.156 <<EOF
          cd /root/smart_menu_bot_prod
          git pull origin main
          ./refresh.sh
        EOF
