name: Deploy to Hetzner on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 91.99.6.156 >> ~/.ssh/known_hosts
    
    - name: Sync files to server
      run: |
        rsync -az --delete \
          --exclude '.git' \
          --exclude '.github' \
          --exclude '.env' \
          ./ root@91.99.6.156:/root/smart_menu_bot_prod/

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=yes -T root@91.99.6.156 <<'EOF'
          set -e
          cd /root/smart_menu_bot_prod
          ./refresh.sh
        EOF
